#!/bin/bash
#https://gist.github.com/noelboss/3fe13927025b89757f8fb12e9066f2fa
# on source:
# $ git remote add production demo@yourserver.com:project.git


TRAGET="/home/apps/hoyh/live"
GIT_DIR="/home/apps/hoyh/git"
BRANCH="master"

while read oldrev newrev ref
do
        # only checking out the master (or whatever branch you would like to deploy)
        if [[ $ref = refs/heads/$BRANCH ]];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
                git --work-tree=$TRAGET --git-dir=$GIT_DIR checkout -f
                echo "Restarting node service: "
                whoami
                pwd
        else
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done
